# Generated by Django 3.1.2 on 2020-10-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jugador',
            options={'ordering': ['name'], 'verbose_name': 'Jugador Verbose', 'verbose_name_plural': 'Jugadores Verbose'},
        ),
        migrations.RemoveField(
            model_name='jugadorhabilidades',
            name='form',
        ),
        migrations.AddField(
            model_name='jugadorhabilidades',
            name='forma',
            field=models.IntegerField(choices=[(1, 'Malo'), (2, 'Pesimo'), (3, 'Regular'), (4, 'Sobresaliente'), (5, 'Excelente')], default=3, verbose_name='Forma'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='name',
            field=models.IntegerField(max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='surname',
            field=models.IntegerField(max_length=40, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='jugadorhabilidades',
            name='defending',
            field=models.IntegerField(choices=[(1, 'Malo'), (2, 'Pesimo'), (3, 'Regular'), (4, 'Sobresaliente'), (5, 'Excelente')], default=3, verbose_name='Defensa'),
        ),
        migrations.AlterField(
            model_name='jugadorhabilidades',
            name='discipline',
            field=models.IntegerField(choices=[(1, 'Malo'), (2, 'Pesimo'), (3, 'Regular'), (4, 'Sobresaliente'), (5, 'Excelente')], default=3, verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='jugadorhabilidades',
            name='experience',
            field=models.IntegerField(choices=[(1, 'Malo'), (2, 'Pesimo'), (3, 'Regular'), (4, 'Sobresaliente'), (5, 'Excelente')], default=3, verbose_name='Experiencia'),
        ),
        migrations.AlterField(
            model_name='jugadorhabilidades',
            name='keeper',
            field=models.IntegerField(choices=[(1, 'Malo'), (2, 'Pesimo'), (3, 'Regular'), (4, 'Sobresaliente'), (5, 'Excelente')], default=3, verbose_name='Guardameta'),
        ),
        migrations.AlterField(
            model_name='jugadorhabilidades',
            name='pace',
            field=models.IntegerField(choices=[(1, 'Malo'), (2, 'Pesimo'), (3, 'Regular'), (4, 'Sobresaliente'), (5, 'Excelente')], default=3, verbose_name='Rápidez'),
        ),
        migrations.AlterField(
            model_name='jugadorhabilidades',
            name='passing',
            field=models.IntegerField(choices=[(1, 'Malo'), (2, 'Pesimo'), (3, 'Regular'), (4, 'Sobresaliente'), (5, 'Excelente')], default=3, verbose_name='Pases'),
        ),
        migrations.AlterField(
            model_name='jugadorhabilidades',
            name='playmaking',
            field=models.IntegerField(choices=[(1, 'Malo'), (2, 'Pesimo'), (3, 'Regular'), (4, 'Sobresaliente'), (5, 'Excelente')], default=3, verbose_name='Creación'),
        ),
        migrations.AlterField(
            model_name='jugadorhabilidades',
            name='scoring',
            field=models.IntegerField(choices=[(1, 'Malo'), (2, 'Pesimo'), (3, 'Regular'), (4, 'Sobresaliente'), (5, 'Excelente')], default=3, verbose_name='Anotación'),
        ),
        migrations.AlterField(
            model_name='jugadorhabilidades',
            name='stamina',
            field=models.IntegerField(choices=[(1, 'Malo'), (2, 'Pesimo'), (3, 'Regular'), (4, 'Sobresaliente'), (5, 'Excelente')], default=3, verbose_name='Condición'),
        ),
        migrations.AlterField(
            model_name='jugadorhabilidades',
            name='technique',
            field=models.IntegerField(choices=[(1, 'Malo'), (2, 'Pesimo'), (3, 'Regular'), (4, 'Sobresaliente'), (5, 'Excelente')], default=3, verbose_name='Técnica'),
        ),
    ]
