# Generated by Django 3.1.2 on 2020-10-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0002_auto_20201005_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='surname',
            field=models.CharField(max_length=40, verbose_name='Apellidos'),
        ),
    ]
